### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/event#10]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [x] crm_lead_to_event_registration - By @cubells - #68 
- [ ] event_contact - By @mikevhe18 - #61 
- [ ] event_multi_image
- [ ] event_project
- [x] event_registration_cancel_reason - By @cubells - #70 
- [x] event_registration_partner_unique - By @cubells - #69 
- [ ] event_product
- [x] event_registration_mass_mailing - By @cubells - #71 
- [ ] event_registration_seat_limit
- [ ] event_track_generate
- [x] partner_event - By @cubells - #64 
- [ ] website_event_contact - By @mikevhe18 - #63 
- [ ] website_event_sale_legal
- [x] website_event_share - By @cubells - #66 
- [x] website_event_filter_selector - By @Yajo - #67
