### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/event#58]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [x] event_contact - By @Yajo - #87 
- [x] event_project - By @chienandalu - #86 
- [x] event_registration_mass_mailing - By @chienandalu - #80
- [x] partner_event - By @chienandalu - #77 
- [x] website_event_excerpt_img - By @chienandalu - #83 
- [x] website_event_filter_selector - By @Yajo - #85 
- [x] website_event_share - By @chienandalu - #82

**Comment by pedrobaeza** [comment]
Wow, we did it! We have completed to migrate all the modules of this repository for v10. Closing the issue.

**Comment by chienandalu** [comment]
:clap: :clap: :clap:

**Comment by gwizo** [comment]
Well done!

**Comment by yajo** [comment]
![](https://media.giphy.com/media/B3ETOq2MtxqOQ/giphy.gif)
